#!/bin/bash
printf "  * Repository:     https://github.com/ssrkarthikeya/dArkOS-R36XX\n"
printf "  * Wiki & Guides:  https://github.com/christianhaitian/darkos/wiki\n"
printf "\e[1;36m======================================================================\e[0m\n\n"
